In [2]:
import torch

In [3]:
my_torch = torch.arange(0,20,2)
print(my_torch)
test = torch.arange(10)
print(test)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Reshape and View

In [4]:
my_torch= my_torch.reshape(2,5)
print(my_torch)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])


Reshape χωρίς να ξέρω τον αριθμό των στοιχείων βάζω -1 στις άγνωστες διαστάσεις

In [5]:
my_torch2= test
my_torch2=my_torch2.reshape(2,-1)
print(my_torch2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [6]:
my_torch3= test
my_torch3=my_torch3.reshape(-1,2)
print(my_torch3)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [7]:
my_torch4= test
my_torch4=my_torch4.reshape(-1,-1) #αυτό είναι λάθος
print(my_torch4)

RuntimeError: only one dimension can be inferred

In [ ]:
my_torch5= test
my_torch5=my_torch5.view(2,5)
print(my_torch5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


Το Reshape και το View κάνουν αναδρομικά update τους τένσορες, δηλαδή εαν μετά αλλα΄ξω τα στοιχεία του τένσορα, αλλάζει και ο reshaped/viewed τένσορας αυτόματα που είναι γραμμένος πιο πίσω

In [ ]:
my_torch6=test
print(my_torch6)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
my_torch7=my_torch6.reshape(2,5)
print(my_torch7)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
my_torch6[1]=666
print(my_torch6)

tensor([  0, 666,   2,   3,   4,   5,   6,   7,   8,   9])


In [ ]:
print(my_torch7) #updated

tensor([[  0, 666,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


Φέτες

In [8]:
my_torch8=test
my_torch8[7]

tensor(7)

In [9]:
my_torch9=my_torch8.reshape(5,2)
print(my_torch9)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
print(my_torch9[:,1])
print(my_torch9[:,1:]) #κρατάει την δομή δηλαδή το επιστρέφει σαν στύλη
print(my_torch9[1,:])
print(my_torch9[1:,:]) #γραμμή απο το 1 και μετά άρα πέρνω όλον εκτώς από την γραμμή 0 (πρώτη)

tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])
tensor([2, 3])
tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


Διαφορές View και Reshape
https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch