Tensor Math

In [1]:
import torch
import numpy as np

Δύο τρόποι να φτιάξω τενσορες και ωραίος τρόπος να κάνω print string και variables

In [2]:
ar=torch.arange(1,5)
tenA = ar.clone().detach() ; print(f'A= {tenA}')
tenB = torch.tensor([5,6,7,8]) ; print(f'B= {tenB}')

A= tensor([1, 2, 3, 4])
B= tensor([5, 6, 7, 8])


Addittion
Το ίδιο πράγμα απλά shorthand σημαίνει ότι δεν καλώ την συνάρτηση γραφοντάς την, είναι κωδικοπρατσούκλη. Αντί να γράφω torch,add() γράφω απλά a+b.

In [3]:
Ab=tenA+tenB ; print(f'shorthand={Ab}')
aB=torch.add(tenA,tenB) ; print(f'longhand={aB}')

shorthand=tensor([ 6,  8, 10, 12])
longhand=tensor([ 6,  8, 10, 12])


Subtraction

In [4]:
Ab=tenB-tenA ; print(Ab)
aB=torch.sub(tenB,tenA) ; print(aB)

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


Multiplication

In [5]:
Ab=tenB*tenA ; print(Ab) ;print()
aB=torch.mul(tenB,tenA) ; print(aB)

tensor([ 5, 12, 21, 32])

tensor([ 5, 12, 21, 32])


Division

In [6]:
Ab=tenB/tenA ; print(Ab) ;print()
aB=torch.div(tenB,tenA) ; print(aB)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

tensor([5.0000, 3.0000, 2.3333, 2.0000])


Remainder (Modulo)

In [7]:
print(tenA,tenB) ; print()

Ab=tenB%tenA ; print(Ab) ;print()

aB=torch.remainder(tenB,tenA) ; print(aB)

tensor([1, 2, 3, 4]) tensor([5, 6, 7, 8])

tensor([0, 0, 1, 0])

tensor([0, 0, 1, 0])


Δύναμη

In [8]:
print(tenA,tenB) ; print()
torch.pow(tenA,tenB)

tensor([1, 2, 3, 4]) tensor([5, 6, 7, 8])



tensor([    1,    64,  2187, 65536])

Άλλως

In [9]:
tenA.add(tenB) #κτλ

tensor([ 6,  8, 10, 12])

Reassignment +=,-=,*=,/=,%=,κτλ


ATTENZIONE ΤΑ ΚΕΛΙΑ ΔΕΝ ΕΙΝΑΙ ΑΝΕΞΆΡΤΗΤΑ ΕΑΝ ΑΛΛΑΞΕΙΣ ΠΙΟ ΚΑΤΩ ΜΙΑ ΜΕΤΑΒΛΗΤΗ ΟΤΑΝ ΤΗΝ ΤΡΕΞΕΙΣ ΠΙΟ ΠΑΝΩ ΕΧΕΙ ΤΗΝ ΑΝΑΝΑΙΩΜΈΝΗ ΤΙΜΉ

In [10]:
tenA = ar.clone().detach() ; print(f'Og: A= {tenA}')
 #reset
tenA+=tenB ; print(f'new A= {tenA}')

tenA = ar.clone().detach() ; print(f'   Reset \nA= {tenA}') #reset
tenA-=tenB ; print(f'new A= {tenA}')

tenA = ar.clone().detach() ; print(f'   Reset \nA= {tenA}') #reset
tenA*=tenB ; print(f'new A= {tenA}')

tenA = ar.clone().detach() ; print(f'   Reset \nA= {tenA}') #reset
tenA%=tenB ; print(f'new A= {tenA}')

tenA = ar.clone().detach() ; print(f'   Reset \nA= {tenA}')  #reset
tenA/=tenB ; print(f'new A= {tenA}') #στην διαίρεση δεν δουλέυει

Og: A= tensor([1, 2, 3, 4])
new A= tensor([ 6,  8, 10, 12])
   Reset 
A= tensor([1, 2, 3, 4])
new A= tensor([-4, -4, -4, -4])
   Reset 
A= tensor([1, 2, 3, 4])
new A= tensor([ 5, 12, 21, 32])
   Reset 
A= tensor([1, 2, 3, 4])
new A= tensor([1, 2, 3, 4])
   Reset 
A= tensor([1, 2, 3, 4])


RuntimeError: result type Float can't be cast to the desired output type Long

Reasignment_

In [ ]:
print(f'Og: A= {tenA}')
tenA.add_(tenB) #REASIGNMENT USING _
print(f'new A= {tenA}') ; print()

tenA = ar.clone().detach() ; print(f'   Reset \nA= {tenA}')#reset

tenA.pow_(tenB) #REASIGNMENT USING _
print(f'new A= {tenA}') ; print()


tenB.div_(tenA) #Το ίδιο και εδώ δεν δουλεύει στην διαίρεση




Og: A= tensor([    1,    64,  2187, 65536])
new A= tensor([    6,    70,  2194, 65544])

   Reset 
A= tensor([1, 2, 3, 4])
new A= tensor([    1,    64,  2187, 65536])



RuntimeError: result type Float can't be cast to the desired output type Long

Creating a Matrix using List Comprehension\
\
Το i στο range(start,finish,step) άρα βγάζει i=1, i=1+3=4 και i=4+3=7\
To j in range(3) αρχίζει από default=0 και πέρνει j=0, j=1, j=2\
\
Δομή List Comprehension\ 
[expression for inner_loop for outer_loop]
άρα\
Στο list comprehension, ο εσωτερικός βρόχος γράφεται πρώτος, αλλά εκτελείται τελευταίος. Όπως είναι λογικό.

    Ο j in range(3) εκτελείται μέσα σε κάθε i.
    Ο i in range(1, 8, 3) αλλάζει μόνο αφού τελειώσουν όλα τα j.

Αυτό συμβαίνει επειδή το list comprehension φτιάχνει πρώτα τα στοιχεία μιας λίστας (άρα πρώτα ο εσωτερικός βρόχος) και μετά επαναλαμβάνει για κάθε νέο στοιχείο στη λίστα (άρα μετά ο εξωτερικός βρόχος).


Άρα ενώ εκτελεί αυτό:\
ΓΙΑ κάθε γραμμή (i)\
    ΓΙΑ κάθε στήλη (j)\
        Υπολόγισε το στοιχείο\
\
\
Απλώς το list comprehension το γράφει αντίστροφα:\
\
Υπολόγισε το στοιχείο ΓΙΑ κάθε στήλη (j) ΓΙΑ κάθε γραμμή (i)\
\
Αυτός είναι ο λόγος που ο i φαίνεται "μετά" στο list comprehension, αλλά στην πράξη είναι ο εξωτερικός βρόχος.





In [12]:
matrix = [[i + j for j in range(3)] for i in range(1, 8, 3)] #List Comprehension

for row in matrix:
    print(row)


matrix_idio = []
for i in range(2, 11, 4):   # ΕΞΩΤΕΡΙΚΟΣ ΒΡΟΧΟΣ (δημιουργεί τις γραμμές)
    row = []
    for j in range(3):     # ΕΣΩΤΕΡΙΚΟΣ ΒΡΟΧΟΣ (δημιουργεί τα στοιχεία της γραμμής)
        row.append(i + j)
    matrix_idio.append(row)

print('')
for row in matrix_idio:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

[2, 3, 4]
[6, 7, 8]
[10, 11, 12]


Tests με μεγαλήτερους τένσορες.

In [13]:
tenA=torch.tensor(matrix) ; tenB = torch.tensor(matrix_idio)

add=tenA+tenB ; print(add) ; print()
sub=tenB-tenA ; print(sub) ; print()
mul=tenA*tenB ; print(mul) ; print()


tensor([[ 3,  5,  7],
        [10, 12, 14],
        [17, 19, 21]])

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

tensor([[  2,   6,  12],
        [ 24,  35,  48],
        [ 70,  88, 108]])



Συμπέρασμα Οι πράξεις αυτές μεταξύ τενσόρων είναι HADAMARD δηλαδή στοιχείο προς στοιχείο άρα Α(1,1)+Β(1,1)=Γ(1,1)